### ISSUE TITLE
geopoint concatenation failing

### ISSUE THREAD

**Issue by getodk-bot** [getodk/javarosa#138]
Originally reported by: **Yaw Anokwa (Bitbucket: [yanokwa](https://bitbucket.org/yanokwa), GitHub: [yanokwa](https://github.com/yanokwa))**

----------------------------------------

"Is there a way to calculate/concatenate something, inside a form, that includes GPS locations?  I keep getting FC errors.

I know how to set the xml up and use concatenation - I want to know about using GPS specifically.  I tried inside a group without success and have quickly run out of ideas.  I'd prefer to handle the work inside the form and not on the backend server.

As a simple example: concat("You are here: ",${geopoint1})  - this fails me.  I can collect several GPS locations but when I add the calculate task it fails."

----------------------------------------
- Bitbucket: https://bitbucket.org/javarosa/javarosa/issue/62

**Comment by grzesiek2010** [comment]
This can be achieved. Sample form: 
[cocnatGeoTest.xlsx](https://github.com/getodk/javarosa/files/12728734/cocnatGeoTest.xlsx)
