### ISSUE TITLE
Evaluate performance of current external secondary instance implementation

### ISSUE THREAD

**Issue by lognaturel** [getodk/javarosa#170]
In #16, initial support for external secondary instances was added. This provides:
- A single way to query external data. [Data preloading](https://opendatakit.org/help/form-design/data-preloading/) exists in Collect to load external CSVs. However, it doesn't allow for querying with sophisticated expressions as requested [here](https://forum.opendatakit.org/t/pulldata-with-two-lookup-values/9435)
- A more XForms-like specification for external data that other members of the ecosystem such as Enketo can adopt
- The potential for "artificial instances" as described [in the initial OpenRosa spec](https://bitbucket.org/javarosa/javarosa/wiki/externalinstances) to query application data such as instances. This could enable things like [this use case](https://forum.opendatakit.org/t/a-dynamic-form-data-lookup-locally-without-server-synchronization/9382)

And perhaps more? Clearly it has some nice potential.

Before the current implementation can be used in any meaningful way, we need to know how performant it is. I suspect that it struggles once the external instances get big at all. We should try to get a sense of what the practical limits are. I'm not sure what the best way to do this is but as a start I might script a way to generate random XML data, generate files of different lengths, build a form that queries that data (e.g. gets the first element where child1 is "foo" and child2 is "bar"), try it out on a physical device and make a table to see how the performance degrades as more records are added (100, 1000, 10000, etc) and maybe as queries get more complex.

**Comment by lognaturel** [comment]
@mdudzinski perhaps you could look into this? @dcbriccetti you probably have some good ideas as well.

**Comment by lognaturel** [comment]
Had a chance to catch up with @mdudzinski and he will try to look at it early Sept and keep us updated here.

**Comment by dcbriccetti** [comment]
I’m doing some experiments with large secondary instance files.

**Comment by yanokwa** [comment]
Here is a form from our friends in Nigeria with a cascading list of states, wards, and LGAS. 

[nigeria-wards.xml.zip](https://github.com/opendatakit/javarosa/files/1332282/nigeria-wards.xml.zip)
[nigeria-wards.xlsx](https://github.com/opendatakit/javarosa/files/1332283/nigeria-wards.xlsx)

**Comment by mdudzinski** [comment]
@dcbriccetti I've seen on Slack that you figured out a few bottlenecks and came up with a few ideas for improvements. Do you have some code already pushed to your fork? If so, could you point mi to the branch or a commit? I'd like to catch up and I find it hard to do it by only following the conversation on slack :)
Thanks in advance!

**Comment by dcbriccetti** [comment]
@yanokwa, thanks for the form. I plan to look at it tomorrow.
@mdudzinski the most recent commit comment here, https://github.com/opendatakit/javarosa/pull/192, along with the Slack conversation from about 20 hours ago should get you up to speed. Let me know how you want to join in, or if you want to take over.

**Comment by mdudzinski** [comment]
@dcbriccetti Thank you!
