### ISSUE TITLE
Distance is not calculated properly when using Geopoint data type

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/javarosa#332]
#### Software versions 
JavaRosa v2.10.0

#### Problem description
Working on https://github.com/opendatakit/javarosa/issues/318 I noticed a problem with a result of distance function calculated using Geopoint data type.
Here is a sample form: 
[distance.xml.txt](https://github.com/opendatakit/javarosa/files/2149758/distance.xml.txt)

and an instance saved using the attached form.

```
<?xml version="1.0" encoding="UTF-8"?>
<distance xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" id="distance" version="2018042401">
   <geoshape>10.12 9.53 0.0 0.0; 10.86 50.14 0.0 0.0; 23.35 77.07 0.0 0.0</geoshape>
   <geotrace>10.12 9.53 0.0 0.0; 10.86 50.14 0.0 0.0; 23.35 77.07 0.0 0.0</geotrace>
   <points>
      <point>10.12 9.53 0.0 0.0</point>
      <point>10.86 50.14 0.0 0.0</point>
      <point>23.35 77.07 0.0 0.0</point>
      <point />
   </points>
   <shape-result>7618634.821750692</shape-result>
   <trace-result>7618634.821750692</trace-result>
   <point-result>1.631765199491293E7</point-result>
   <meta>
      <instanceID>uuid:7dd91ba9-db27-4a02-b485-b25c9967aaab</instanceID>
   </meta>
</distance>
```

As you can see in all three cases we use the same coordinates but a result for Geopoint data is different.
It would be also good to check area calculations for Geopoint data type.

**Comment by dcbriccetti** [comment]
Why is that empty <point> tag there? I think it’s a factor.

**Comment by dcbriccetti** [comment]
How can I use that form in Collect? That’s what you’re doing, right? I get a dialog box saying, “Add One More Group? Add another "null" group?

**Comment by lognaturel** [comment]
@dcbriccetti The body is wrong. You can replace it with something like:
```
        <repeat nodeset="/distance/points">
            <input ref="/distance/points/point">
                <label>Get point</label>
            </input>
        </repeat>
```
You'll still see that dialog but you should then be able to add a point.

**Comment by lognaturel** [comment]
Actually, the instance is also wrong. It should be 
```
   <points>
      <point>10.12 9.53 0.0 0.0</point>
  </points>
  <points>
      <point>10.86 50.14 0.0 0.0</point>
  </points>
  <points>
      <point>23.35 77.07 0.0 0.0</point>
  </points>
  <points>
      <point />
   </points>
```

@grzesiek2010 you generated this form by hand, right?

**Comment by grzesiek2010** [comment]
> @grzesiek2010 you generated this form by hand, right?

No, actually @dcbriccetti is an author of this form:
https://github.com/opendatakit/javarosa/blob/master/resources/org/javarosa/core/util/distance.xml

**Comment by grzesiek2010** [comment]
> How can I use that form in Collect? That’s what you’re doing, right? I get a dialog box saying, “Add One More Group? Add another "null" group?

You can just add one group and save such a form, results should be in an instnce file like the one I attached.

**Comment by dcbriccetti** [comment]
>body is wrong

I changed the form to this
```
<?xml version="1.0"?>
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:ev="http://www.w3.org/2001/xml-events"
        xmlns:h="http://www.w3.org/1999/xhtml" xmlns:jr="http://openrosa.org/javarosa"
        xmlns:orx="http://openrosa.org/xforms/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <h:head>
        <h:title>Distance of a geoshape, geotrace, or set of geopoints</h:title>
        <model>
            <instance>
                <distance id="distance" version="2018070402">
                    <points>
                        <point></point>
                    </points>
                    <point-result/>
                    <meta>
                        <instanceID/>
                    </meta>
                </distance>
            </instance>
            <bind nodeset="/distance/points/point" type="geopoint"/>
            <bind calculate="distance( /distance/points/point )" nodeset="/distance/point-result" type="string"/>
            <bind calculate="concat('uuid:', uuid())" nodeset="/distance/meta/instanceID" readonly="true()" type="string"/>
        </model>
    </h:head>
    <h:body>
        <repeat nodeset="/distance/points">
            <input ref="/distance/points/point">
                <label>Get point</label>
            </input>
        </repeat>
    </h:body>
</h:html>
```
I collected a few points around the house, and got this data back:
```
    <points>
        <point>37.90108037 -122.09602891 66.80000305175781 5.0</point>
    </points>
    <points>
        <point>37.90107935 -122.09602963 66.19999694824219 5.0</point>
    </points>
    <points>
        <point>37.90108181 -122.09602914 66.0 5.0</point>
    </points>
    <points>
        <point>37.90106421 -122.09603424 65.4000015258789 5.0</point>
    </points>
    <point-result>2.414866060962149</point-result>
```
I haven’t checked the correctness yet, but 2.4 meters seems very small. I captured logging data and all three pairs of points were used to calculate distances. I don’t recall if our algorithm is supposed to work with distances in the units or low tens of meters.

**Comment by lognaturel** [comment]
As described above, the form definition's structure was wrong. While fixing it in a test for #574, I put in the values from the form @grzesiek2010 was working with and confirmed that the result for the corrected geopoint repeat is the same as for a trace or shape.

See [geopoint-nodeset-distance.xml.zip](https://github.com/getodk/javarosa/files/4626164/geopoint-nodeset-distance.xml.zip) for a form definition with those values in a geopoint nodeset.
