### ISSUE TITLE
Allow distance() function with two arguments input to calculate distance between 2 points

### ISSUE THREAD

**Issue by khalifeserge** [getodk/javarosa#386]
I noticed that the distance() function is still having some issues based on this #332 . I am proposing that the function be modified slightly to allow distance() to be calculated based on 2 points input ( 2 arguments ). In many of my forms I have a geopoint ( with placement appearance) and another one as a plain GPS point. The reason behind this approach is that I usually load an offline map with the points that need to be visited then I ask the enumerator to mark the location he is at using the placement map and then at the end of the survey, the enumerator takes a plain GPS point. I then calculate the distance using 

6371000*2*asin(sqrt(   pow(sin((selected-at(${auto_loc},0) - selected-at(${usr_loc},0))*pi() div   360),2)+cos(selected-at(${usr_loc},0)*pi()div   180)*cos(selected-at(${auto_loc},0)*pi() div   180)*pow(sin((selected-at(${auto_loc},1)-selected-at(${usr_loc},1))*pi()div   360),2)))

To approximate the distance between the auto_loc point and the usr_loc point and if the distance is larger then X meters I make the enumerator correct one of the input. 

Using the distance function would make this a lot neater distance(${usr_loc},${auto_loc}).

Another need for this behavior is when i am collecting info about electric utility lines or sewers or any physical network of points the enumerator gos to each corner structure or structure with equipment on it and collect the info. Then in my form I always take the distance between the current point and the previous point to ensure that the enumerator is digitising the network at a dsente resolution.

I have not programmed in Java in ages but I am willing to try to make this change if this request is approved.

**Comment by lognaturel** [comment]
Apologies for the silence on this issue. 

I recently closed #332 and added more tests for the distance and area function and saw this. In general, please use [the forum](https://forum.getodk.org) as the first place to go for support as it goes to a broader audience.

You can concatenate two geopoints separated by a semicolon (;) to achieve what you need. I've filed a documentation issue to make this more clear: https://github.com/getodk/docs/issues/1222.
