### ISSUE TITLE
Fail gracefully when an external secondary instance is not found

### ISSUE THREAD

**Issue by lognaturel** [getodk/javarosa#444]
#### Problem description
Currently, a missing external secondary instance results in failure to parse a form. This is a problem because clients like Validate (https://github.com/opendatakit/validate/pull/66) or Aggregate don't need to have those external instances to do what they need to do. In fact, even form-filling clients like Collect may not need those files if, for example, they are used in optional questions. 

#### Steps to reproduce the problem
Try to parse a form such as [nigeria_wards_external.xml.txt](https://github.com/opendatakit/javarosa/files/3263461/nigeria_wards_external.xml.txt) that refers to external secondary instances. An exception will be thrown from `verifyItemsetBindings`. Something will also need to be done in `populateDynamicChoices` for clients that do something with the choices.

#### Expected behavior
No exception is thrown. Clients have a way of detecting that the instance files were unavailable and can choose what to do.

**Comment by ggalmazor** [comment]
I've started poking around this issue and I'm getting an error _before_ `FormInstanceParser.verifyItemsetBindings()`. It turns out that the `XFormParser.parseDoc()` fails to add the non-main instance into the `FormDef` at line 476-ish:

```java
if (instanceSrc != null && instanceSrc.toLowerCase().startsWith("jr://file/")) {
    final ExternalDataInstance externalDataInstance;
    try {
        externalDataInstance = ExternalDataInstance.build(instanceSrc, instanceId);
    } catch (IOException | UnfullfilledRequirementsException | InvalidStructureException |
            XmlPullParserException | InvalidReferenceException e) {
        String msg = "Unable to parse external secondary instance";
        logger.error(msg, e);
        throw new XFormParseException(msg + ": " + e.toString(), instance);
    }
    _f.addNonMainInstance(externalDataInstance);
}
```

**Comment by lognaturel** [comment]
Good point, @ggalmazor! I /thought/ the `verifyItemsetBindings` exception was the one I saw in Validate but perhaps I misunderstood.

> We might be unable to deal with this issue until we figure out how to lazy-load external instances.

True. Even more reason to go with the narrow Validate fix for now and then to come back here.
