### ISSUE TITLE
Add zero-argument variants for string-length and normalize-space functions

### ISSUE THREAD

**Issue by lognaturel** [getodk/javarosa#468]
See https://www.w3.org/TR/1999/REC-xpath-19991116/#function-string-length

**Comment by abdulazizali77** [comment]
hi @lognaturel can i pick this up?

**Comment by lognaturel** [comment]
That would be wonderful, @abdulazizali77! Please ask if you have any questions either here or [in Slack](https://slack.opendatakit.org).
