### ISSUE TITLE
Type conversion may not be as described by XPath spec

### ISSUE THREAD

**Issue by lognaturel** [getodk/javarosa#562]
https://forum.opendatakit.org/t/how-to-compare-2-calculated-values/5588 for sample form.

It should be possible to sum fields of type string because they should automatically be coerced to numbers.

More context: https://github.com/XLSForm/xlsform.github.io/issues/71#issuecomment-224322744 and https://github.com/XLSForm/pyxform/issues/70#issuecomment-599660252

We should at least have tests to document the current behavior.

**Comment by grzesiek2010** [comment]
This works as expected now so we can close the issue.
