### ISSUE TITLE
Media files are not displayed in select questions if choice_filter is used

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/javarosa#575]
#### Software versions 
All versions

#### Problem description
Media files are not displayed in select questions if choice_filter is used. The problem has been reported on the forum: https://forum.getodk.org/t/embedded-images-in-select-one-questions-in-groups/26378/4

#### Steps to reproduce the problem
Test the attached form: 
[choiceFilterWithImages.zip](https://github.com/getodk/javarosa/files/4643573/choiceFilterWithImages.zip)

#### Expected behavior
Media files should be displayed.

**Comment by macdude357** [comment]
I'm new to how all this works but in looking at the code, tests and docs, it seems that the line `<label ref="label" />` refers to the text label defined in the instance "dogcats" and not the translation in the itext block.  There is an example of this in the unit tests that uses ` <label ref="jr:itext('/data/image:label')"/>` to reference an image in an `<itext>` block.

**Comment by lognaturel** [comment]
@macdude357 you're absolutely correct. That makes it a `pyxform` issue, then. I've filed it at https://github.com/XLSForm/pyxform/issues/464.
