### ISSUE TITLE
substr() returns results in lower-case

### ISSUE THREAD

**Issue by yanokwa** [getodk/javarosa#59]
From kderra@gmail.com and https://groups.google.com/d/msg/opendatakit/bzUx6paP8MU/e4W7bOrTxncJ

> I make a pull data in the form with cascading selct. One of the key variable is a composite ID which is initialy in upper case. e.g id=RE067. When I want to keep the 2first two letters of the id variable, I got "re" and not "RE". I used this function : substr(${id},0,2)

**Comment by dcbriccetti** [comment]
Interesting. It looks like it’s not the substr implementation. This test passes:

`testEval("substr('Hello',0, 2)", "He");`

**Comment by KDerra** [comment]
[Cascading_indiv_Karim_June2017.xlsx](https://github.com/opendatakit/javarosa/files/1048000/Cascading_indiv_Karim_June2017.xlsx)

Hi Yaw,
I attached a very small test form.
Regards,
Karim

**Comment by KDerra** [comment]
Dear dcbriccetti,
Pls can you more explain to me how it works ?
Regards,
Karim

**Comment by dcbriccetti** [comment]
Hi @KDerra. That transformation isn’t happening from substr, so perhaps it is related to $(id).

**Comment by KDerra** [comment]
Thanks dcbriccetti. another solution?

**Comment by grzesiek2010** [comment]
I can confirm that `substring` functions work well. I've used this form for testing: 
[substringTest.xlsx](https://github.com/getodk/javarosa/files/12727027/substringTest.xlsx)
The form attached above used `cascading_select` question type that is not supported anymore. Maybe that was the cause. I think we can close this issue.
