### ISSUE TITLE
Survey user properties spoiled in a few cases

### ISSUE THREAD

**Issue by mauricioguell-sagaci** [getodk/javarosa#592]
#### Software versions 
`implementation('org.opendatakit:opendatakit-javarosa:2.17.2')`  
Android

#### Problem description
In a really small percentage of the cases (around once in 5000), when the user sends the survey it arrives with the user properties spoiled and we have to manually fix them. 
Things like this: <simserial /><subscr46ccfd1726c378</deviceid>
When it should be something like this: <simserial /><subscriberid /><deviceid>TECNO-46ccfd1726c378</deviceid>

#### Steps to reproduce the problem
Unknown, it happens only in a few cases.

#### Other information 
That is the way I get the survey as String:
`formController.filledInFormXml.toString`

My PropertyManager it's almost the same as Collect one. 

There is something I could do? 

Cheers,
Mauricio Güell

**Comment by lognaturel** [comment]
As I think you've already surmised, this has to do with the `PropertyManager`, not with JavaRosa. And in all likelihood it has to do with the operating system interaction, not with your implementation. Unfortunately I don't think there's anything you can do about it.
