### ISSUE TITLE
Restricting fake location application while collecting gps points with Collect android app

### ISSUE THREAD

**Issue by Kalyan-Lama** [getodk/javarosa#593]
#### Software versions 
`ODK Collect v1.27.3` also `KoBoCollect v1.27.3`

#### Problem description

Enumerators are able to use fake location application while collecting gps points with `Collect android app`. 

#### Steps to reproduce the problem

* Enable the fake location app.
* Collect gps data in `Collect android app`.
* You are able to collect fake gps location.

#### Expected behavior

While collecting data with `Collect android app` would it be possible to disable the fake location app that generates fake location?

#### Other information 

For details, please have a look at the community forum for the detailed discussion:

https://community.kobotoolbox.org/t/fake-location-detection/11522

**Comment by lognaturel** [comment]
Not related to JavaRosa. Feature thread at https://forum.getodk.org/t/restricting-fake-location-application-while-collecting-gps-points-with-collect-android-app/29231
