### ISSUE TITLE
Support quotes, escaped commas, and other CSV formatting in external CSV files

### ISSUE THREAD

**Issue by lognaturel** [getodk/javarosa#616]
#### Software versions 
All

#### Problem description
CSVs are split on commas with no accounting for standard CSV formatting.

#### Steps to reproduce the problem
[select-one-file.zip](https://github.com/getodk/javarosa/files/5700809/select-one-file.zip)

#### Expected behavior
Standard CSV formatting is handled.

**Comment by dcbriccetti** [comment]
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/55099/112928387-6445f800-90cb-11eb-9994-cb7c5bcb3023.png">

Hi. Does this cover the cases?

**Comment by dcbriccetti** [comment]
Shall we follow this spec?
https://tools.ietf.org/html/rfc4180
It doesn’t mention “escaped commas”. I’m assuming you mean commas appearing in a field that is delimited by double quotes.

**Comment by lognaturel** [comment]
Yes, definitely that spec, sorry I didn't link to it! https://github.com/getodk/collect/pull/4472/files#diff-b1032cb8006c5ceebbece74c16567d3e3dbb5b53c01fa61ac35ba416ccd6def6 are tests I wrote for behavior *writing* a CSV recently. I would expect your tests to be symmetric to those (and it's a good opportunity to make sure my cases match the spec).

**Comment by lognaturel** [comment]
> commas appearing in a field that is delimited by double quotes

Yes, exactly.

**Comment by dcbriccetti** [comment]
Any reason not to use, say, Apache Commons CSV, for this, rather than writing our own parser? At around 50KB, the jar is pretty small. Version 1.6 will run under Java 1.7.

**Comment by lognaturel** [comment]
> Any reason not to use, say, Apache Commons CSV, for this

I can't really think of one as long as binary size and performance are similar to native. Might be worth seeing whether we discussed it previously? If it means having an extra large structure in memory that might not be reasonable, for example.

**Comment by lognaturel** [comment]
https://github.com/getodk/javarosa/pull/397 and https://github.com/getodk/javarosa/issues/417 + https://github.com/getodk/javarosa/pull/452 make for some good, light reading with some things to look out for. 😊

**Comment by dcbriccetti** [comment]
I quickly looked over those three items and don’t see problems with swapping out our trivial CSV parsing code (essential a split on “,”) with something complete and correct. All the existing, and the new tests pass when using Commons CSV.

**Comment by lognaturel** [comment]
This probably should be a separate issue but capturing it here for now in case the Apache commons lib @dcbriccetti is using solves the problem -- Excel exports with semicolons instead of commas by default with certain locales. Very annoying but would be ideal to support semicolon delimiters as well.

**Comment by joshuaberetta** [comment]
Hi @dcbriccetti, here's an additional case to be aware of:
Community issue: https://community.kobotoolbox.org/t/select-options-missing-in-select-one-from-file/20846
Discussion: https://getodk.slack.com/archives/C35ENHA64/p1627420759224700
