### ISSUE TITLE
`CompareChildToAbsoluteExpression` should support more expressions

### ISSUE THREAD

**Issue by seadowg** [getodk/javarosa#726]
As discussed in https://github.com/getodk/javarosa/pull/722. As this class is used as the backbone of the new predicate/choice filter optimisations, this will allow us to optimise more forms.

Expression forms we should support:

- [x] `<function>(<relative path expression>, <absolute path expression>)`
- [x] `<relative path expression> <operator> <context relative expression>` ("context relative expression" is one starting with with a `current()` or `instance()`)

**Comment by seadowg** [comment]
@lognaturel does it look like this covers everything we've discussed?

**Comment by lognaturel** [comment]
Sorry about the radio silence. I agree with your analysis so far but haven't had a chance to think more deeply about it yet. Hoping to do so mid next week.
