### ISSUE TITLE
Move Entities package to Collect

### ISSUE THREAD

**Issue by lognaturel** [getodk/javarosa#778]
Entities functionality is currently in an `entities` package: https://github.com/getodk/javarosa/tree/master/src/main/java/org/javarosa/entities

The functionality is very Collect-specific and leverages JR's public API. Moving it into Collect will allow for easier iteration and guarantee that loose coupling is maintained.

As far as we know, there are currently no non-Collect consumers of JR so this change should not have broad negative impact. We'll make it a major version release.

**Comment by grzesiek2010** [comment]
Done in https://github.com/getodk/collect/pull/6236 and https://github.com/getodk/javarosa/pull/784
